// Function to Generate Help Manual as PDF
function generateHelpManual() {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text("Splash Cloud - Help Manual", 10, 20);
  
    doc.setFontSize(12);
    doc.text("Features:", 10, 30);
    doc.text(
      "1. Load Geometry: Use the 'Load Geometry' button to load .STL files into the viewer.\n" +
        "2. Change Background: Select different background colors using the dropdown.\n" +
        "3. Toggle Axes: Show or hide the axes helper in the scene.\n" +
        "4. Reset Camera: Resets the view to the initial orientation.\n" +
        "5. 3D Viewer: Use the mouse to rotate, zoom, and pan in the 3D space.",
      10,
      40
    );
  
    doc.setFontSize(10);
    doc.text("Generated by Splash Cloud.", 10, 180);
    doc.save("Splash_Cloud_Help_Manual.pdf");
  }